import { readdir, readFile, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import matter from 'gray-matter';
import { marked } from 'marked';
import { z } from 'zod';

const root = process.cwd();
const contentRoot = path.join(root, 'src', 'content');
const outputFile = path.join(root, 'src', 'app', 'generated', 'content-manifest.generated.ts');

const schema = z.object({
  title: z.string().min(1),
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),
  locale: z.enum(['pt', 'en']),
  type: z.enum(['project', 'article', 'lab', 'decision', 'page']),
  summary: z.string().min(1),
  status: z.string().optional(),
  tags: z.array(z.string()).default([]),
  publishedAt: z.string().optional(),
  updatedAt: z.string().optional(),
});

async function walk(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const full = path.join(directory, entry.name);
      return entry.isDirectory() ? walk(full) : full;
    }),
  );
  return files.flat().filter((file) => file.endsWith('.md'));
}
const files = await walk(contentRoot);
const entries = [];

for (const file of files) {
  const raw = await readFile(file, 'utf8');
  const parsed = matter(raw);
  const meta = schema.parse(parsed.data);
  await marked.parse(parsed.content);
  entries.push({
    ...meta,
    source: path.relative(root, file).replaceAll('\\', '/'),
  });
}

entries.sort((a, b) => a.slug.localeCompare(b.slug));
await mkdir(path.dirname(outputFile), { recursive: true });

const generated =
  `// Generated by tools/content/build-content.mjs. Do not edit.\n` +
  `export const contentManifest = ${JSON.stringify(entries, null, 2)} as const;\n`;

await writeFile(outputFile, generated, 'utf8');
console.log(`Validated ${entries.length} content entries.`);
